modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="tpoffline"
version="${version}"
displayName="TpOffline"
description="传送到离线玩家最后下线位置，指令 /tpo <玩家名>（Forge 版）"
authors="ChenRay"

[[dependencies.tpoffline]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.tpoffline]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
